### ISSUE TITLE
Delete v1alpha

### ISSUE THREAD

**Issue by parthea** [googleapis/python-analytics-data#156]
google.analytics.data_v1alpha [here](https://github.com/googleapis/python-analytics-data/tree/main/google/analytics/data_v1alpha) is [no longer being updated](https://github.com/googleapis/googleapis-gen/tree/master/google/analytics/data) and should be removed. Perhaps as a first step, we could emit a warning when the client is imported to let users know that they should migrate to v1beta [here](https://github.com/googleapis/python-analytics-data/tree/main/google/analytics/data_v1beta).

Googlers, see b/194934063.

**Comment by abomhamd** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P2DSV22MVY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P2DSV22MVY');
</script>

**Comment by suztomo** [comment]
v1alpha is still here https://github.com/googleapis/python-analytics-data/tree/main/google/analytics/data_v1alpha

**Comment by parthea** [comment]
Closing as obsolete
