### ISSUE TITLE
I think this should be "metric.custom_definition" instead of "dimension.custom_definition."

### ISSUE THREAD

**Issue by manuzrpEd** [googleapis/python-analytics-data#169]
https://github.com/googleapis/python-analytics-data/blob/6583d1d3c54ee1bc0edeec835a0d0d2319c13d9e/samples/snippets/get_common_metadata.py#L64

**Comment by parthea** [comment]
Hi @ikuleshov,
Please could you take a look?

**Comment by manuzrpEd** [comment]
old issue
