### ISSUE TITLE
Do this project really support custom Dimension?

### ISSUE THREAD

**Issue by jiamo** [googleapis/python-analytics-data#229]
I follow https://developers.google.com/analytics/devguides/reporting/data/v1/advanced#event-scoped_custom_dimensions
and register the customUser dim.

In web console:  I can query the result. But in latest api: it doesn't work. The api response don't raise exception which mean it can recognize the custom dim. However it don't return what the web console return and it is empty

the dim was passed like `Dimension(name=customUser:ab_test)`

**Comment by parthea** [comment]
@ikuleshov, please could you take a look?

**Comment by ikuleshov** [comment]
@jiamo Please make sure the custom dimension name is enclosed in quotes
`Dimension(name="customUser:ab_test")`

The client library just passes the dimension name to the Data API along with the rest of the query, so as long as the query works in the [API Explorer](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport?apix=true), it should work the same using the client library.
