### ISSUE TITLE
How to use Access token with this package?

### ISSUE THREAD

**Issue by abhanan93** [googleapis/python-analytics-data#244]
Hi!
I need to use this package to fetch our customers' GA events from their specified GA4 view id. We already have authenticated our application with users' Google account and populated our database with their ACCESS and REFRESH tokens. Is there a way to plug in existing Access and Refresh tokens with this python client or do I only have to rely to service account JSON file?

I have already explored the [documentation](https://googleapis.dev/python/google-api-core/latest/auth.html) to some extent.

Thanks!

**Comment by hnandiwada** [comment]
+1. We also have a developer token, client ID, client secret, and refresh token for each of our customers. For the ads client, we are able to generate a service with
```
    config_dict = {
        "developer_token": "developer_token",
        "client_id": "client_id",
        "client_secret": "client_secret",
        "refresh_token": "refresh_token",
        "version": "v10",
        "use_proto_plus": True,
    }
    googleads_client = GoogleAdsClient.load_from_dict(config_dict)
```
We can also generate credentials like this:
```
        token_uri = "https://oauth2.googleapis.com/token"
        credentials = google.oauth2.credentials.Credentials(
            token=access_token,
            token_uri=token_uri,
            client_id="client_id",
            client_secret=["client_secret"],
        )
```
Is there a way to use either of these two methods to authenticate in the AnalyticsData or AnalyticsAdmin libraries?

**Comment by hnandiwada** [comment]
Solved! We actually were able to pass in the second Credentials object like so
```
        token_uri = "https://oauth2.googleapis.com/token"
        credentials = google.oauth2.credentials.Credentials(
            token=access_token,
            token_uri=token_uri,
            client_id=client_id,
            client_secret=["client_secret"],
        )
       service = BetaAnalyticsDataClient(credentials=credentials)
```
Turns out the return type of `google.oauth2.credentials.Credentials` is the same as the return type of the credentials from the [oauth quickstart](https://github.com/googleapis/python-analytics-data/blob/main/samples/snippets/quickstart_oauth2.py#L57-L75)
