### ISSUE TITLE
Beeing able to Serialize the RunReportResponse to JSON

### ISSUE THREAD

**Issue by daniel-lopez-puig** [googleapis/python-analytics-data#260]
Having a web application that uses python as backend makes very interesting having a JSON response.

Would be very useful that RunReportResponse class had a method to convert response to JSON.

**What i tried?**
```
def view():
...
   client = BetaAnalyticsDataClient()
   request = RunReportRequest(...)
   response=client.run_report(request)

return JsonResponse(json.dumps(response))
...

# Error:
# TypeError: Object of type RunReportResponse is not JSON serializable
```

**What could be a good solution**
Create a method that returns a serialized JSON response like:
`RunReportRequest.toJSON()`

Thank you very much for your time

**Comment by benhonda** [comment]
Hi! I ran into the same issue and used `proto.Message.to_json(...)` to resolve it, like this:

```python
import proto
...
client = BetaAnalyticsDataClient()
request = RunReportRequest(...)
response = client.run_report(request)
json_req = proto.Message.to_json(response)
```

**Comment by daniel-lopez-puig** [comment]
Thanks @benhonda !
I could make it work with:
```python
from google.protobuf.json_format import  MessageToJson
client = BetaAnalyticsDataClient()
request = RunReportRequest(...)
response = client.run_report(request)
json_response = MessageToJson(response._pb)
```
