### ISSUE TITLE
INVALID_ARGUMENT for average on custom metrics with accents

### ISSUE THREAD

**Issue by GDev30** [googleapis/python-analytics-data#270]
Hello,

I want to get an average on a custom metric with accents (example : "durée" [= "Duration" in French] ).

I get this error:

```
{
"message": "Metric names must only contain letters, numbers, or _. Received a metric name = averageCustomEventdurée",
"code":3,
"status": "INVALID_ARGUMENT",
"details":[]
}

```

Do you have a solution to this problem ?
Thanks you

Note :
- The "customEvent:durée" metric is OK 
- The custom metric "averageCustomEvent:durée" is available in metrics when I look at them via "https://analyticsdata.googleapis.com/v1beta/{name=properties/*/metadata}"

**Comment by brettsneed** [comment]
To make this work today, you'll need to create "averageCustomEventduree" as a metric expression defined in the API request without the accent. For example,
```
{
 "name": "averageCustomEventduree",
 "expression": "customEvent:durée/countCustomEvent:durée"
 }
 ```
 
We'll look into supporting average custom metrics with accents in the future.
 
Thanks,
Brett Sneed
The Google Analytics Team

**Comment by parthea** [comment]
I'm going to close this issue as a response was provided but please feel free to open a new issue with more information.
