### ISSUE TITLE
This line is not working and keep throwing an error

### ISSUE THREAD

**Issue by jchevreau** [googleapis/python-analytics-data#275]
https://github.com/googleapis/python-analytics-data/blob/15f481075158d77465a90bc8f5e6d37a6f298b5d/samples/snippets/quickstart_json_credentials.py#L52

I am trying to set my service account via this method but I keep getting an error as the code constantly wants to look for my environment variable. Has anyone been truly successful on using this line?

**Comment by SStembridge** [comment]
Likely related to this: https://github.com/googleapis/python-analytics-data/issues/177#issuecomment-1242557914

**Comment by suztomo** [comment]
Closing for duplicate https://github.com/googleapis/python-analytics-data/issues/177
