### ISSUE TITLE
pageLocation dimension not working with custom dimension

### ISSUE THREAD

**Issue by JefersonParraVeredata** [googleapis/python-analytics-data#322]
Hi,

I'd like to know if you have details of this error that i'm presenting in the last days.

![image](https://user-images.githubusercontent.com/82390010/207130984-e53a7042-a957-4e08-b9ff-cfe856e51afb.png)

the pageLocation dimension not working with custom dimension.

#### Code examples

`
request_client = RunReportRequest(
            property=f'properties/{settings.GA_PROPERTY_ID}',
            dimensions=[
                Dimension(name='date'),
                Dimension(name='eventName'),
                Dimension(name='pageLocation'),
                Dimension(name='pageTitle')
            ],
            metrics=[
                Metric(name='screenPageViews')
            ],
            date_ranges=[
                DateRange(
                    start_date='30daysAgo',
                    end_date='today'
                )
            ],
            dimension_filter=FilterExpression(
                and_group=FilterExpressionList(
                    expressions=[
                        FilterExpression(
                            filter=Filter(
                                field_name='customUser:vd_client_id',
                                string_filter=Filter.StringFilter(value='1', match_type=Filter.StringFilter.MatchType.EXACT)
                            )
                        ),
                        FilterExpression(
                            filter=Filter(
                                field_name='eventName',
                                string_filter=Filter.StringFilter(value='page_view', match_type=Filter.StringFilter.MatchType.EXACT)
                            )
                        )
                    ]
                )
            ),
            order_bys=[
                OrderBy(dimension=OrderBy.DimensionOrderBy(dimension_name='date', order_type=OrderBy.DimensionOrderBy.OrderType.ALPHANUMERIC), desc=True)
            ]
        )
`

#### Environment details

  - Python version: Python 3.9.5
  - pip version: 22.2.2
  - google-analytics-data: 0.9.0

**Comment by brettsneed** [comment]
pageLocation is not compatible with custom dimensions. To learn more, see https://developers.google.com/analytics/devguides/reporting/data/v1/announcements/20221201-compatibility-changes. pageLocation is one of query string dimensions that is only compatible with a few dimensions & metrics. The guide lists all dimensions & metrics that are compatible with query string dimensions.

Thanks,
Brett Sneed
The Google Analytics Team
