### ISSUE TITLE
No way to set system parameters e.g. quotaUser

### ISSUE THREAD

**Issue by 3dbrows** [googleapis/python-analytics-data#326]
#### Environment details

  - OS type and version: Ubuntu 22.10
  - Python version: 3.10.7
  - pip version: 22.2
  - `google-analytics-data` version: 0.15.0

The [v1beta discovery document ](https://analyticsdata.googleapis.com/$discovery/rest?version=v1beta) shows various parameters we can set, such as `quotaUser`. These are documented on the [System Parameters page](https://cloud.google.com/apis/docs/system-parameters).

But how do we set such parameters using the `BetaAnalyticsDataClient`? It doesn't appear to be possible to set `quotaUser` on a `BetaAnalyticsDataClient`, nor even by trying to use a `BetaAnalyticsDataRestTransport` and hoping for some way to set URI query parameters. It also seems unlikely that a query interceptor can be of much help because that can only edit (for example) the body `RunReportRequest` or similar.

It appears that the [Google API Client for Python](https://github.com/googleapis/google-api-python-client) supports `quotaUser`.

Three questions:
1. Although not recommended, _can_ the above-linked `Google API Client for Python` be used for the `Google Analytics Data API v1` instead?
2. Is `quotaUser` considered deprecated for the `Google Analytics Data API v1`?
3. If the answers to the above are "no" and "no", can we take this issue to be a feature request to support system parameters in this `Python Client for Analytics Data API`?

**Comment by 3dbrows** [comment]
I'm wondering if the correct answer here is:
* Find the desired parameter on the [System Parameters page](https://cloud.google.com/apis/docs/system-parameters), and note its header name in lowercase, e.g. `x-goog-quota-user`
* Create a tuple with this header name and value, and pass it to the metadata as in the following:
```
run_report(
  {
    # snip
  },
  metadata=[("x-goog-quota-user", "foobar")],
)
```

**Comment by hapdotpy** [comment]
Hi @3dbrows, any chance you've figured this out?
I'm facing the same issue but with `RunReportRequest`...

**Comment by 3dbrows** [comment]
Hi @hapdotpy . I think my second comment is how to do it. The metadata argument seems to correspond to request headers.

**Comment by parthea** [comment]
I'm going to close this issue as resolved but please feel free to open a new issue with more information.
