### ISSUE TITLE
How to create funnel fallout report (shopping behaviour report)?

### ISSUE THREAD

**Issue by roopamdad-ck** [googleapis/python-analytics-data#349]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by parthea** [comment]
Hi @roopamdad-ck,

Sample code was added in #258. I'm going to close this issue but please feel free to open a new issue with more information.
