### ISSUE TITLE
Distinct/Unique users on conversions event

### ISSUE THREAD

**Issue by fijar-lazuardy** [googleapis/python-analytics-data#354]
I want to automate and make my own dashboard which combines my own data with Google Analytics [e.g](https://i.stack.imgur.com/1YQXC.png)
Picture above is data that I want to extract. To achieve it, I'm using this library and using Metrics defined in the API (I'm using custom conversions event). I manage to get total of data logged (yellow circle) but what I want is distinct users that log the event (blue circle). I tried to extract all possible metrics from metrics metadata ( https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/getMetadata) but can't find all conversions related metrics that extract data I want. I need help

**Comment by parthea** [comment]
Please use the resources on [this support page](https://developers.google.com/analytics/devguides/reporting/data/v1/help) to reach out directly to the API team for API specific support. If this is a request for a new feature, please submit the feature request [here](https://developers.google.com/analytics/devguides/reporting/data/v1/help#developer-feature-requests). I'm going to close this issue but please feel free to open a new issue with more information.
