### ISSUE TITLE
How to access custom dimension and metrics

### ISSUE THREAD

**Issue by sree80** [googleapis/python-analytics-data#36]
Below is the code to access the standard metrics and dimension, what should i do to access custom dimension and metrics.

request = RunReportRequest(entity=Entity(property_id=property_id),
                               dimensions=[Dimension(name='city')],
                               metrics=[Metric(name='activeUsers')],
                               date_ranges=[DateRange(start_date='2020-03-31',
                                                      end_date='today')])

**Comment by sree80** [comment]
another question, I have a event name = click and this event has different metrics/key like campaign, session, link_url, link_domain. how do I access all the metrics/key for that event name = click.

**Comment by sree80** [comment]
can I get a reply soon. I am blocked on this task related to pulling data from google analytics data

**Comment by ikuleshov** [comment]
Hello,

This article explains how to access custom dimensions and metrics:

https://developers.google.com/analytics/devguides/reporting/data/v1/advanced#event-scoped_custom_dimensions

**Comment by sree80** [comment]
request = RunReportRequest(entity=Entity(property_id=property_id),
                               dimensions=[Dimension(name='EventName')],
                               metrics=[Metric(name='EventCount')],
                               date_ranges=[DateRange(start_date='2021-01-31',
                                                      end_date='today')])

    response = client.run_report(request)

This is what I have. can you please give an example.

**Comment by jiamo** [comment]
you need add prefix `customEvent:` or `customUser`. However I add but result was empty
