### ISSUE TITLE
How to access event and metric ?

### ISSUE THREAD

**Issue by sree80** [googleapis/python-analytics-data#37]
Question 1 )

How to access multiple dimensions and Metrics ? Below I can access a single Dimension and Metrics

request = RunReportRequest(entity=Entity(property_id=property_id),
                               dimensions=[Dimension(name='EventName')],
                               metrics=[Metric(name='EventCount')],
                               date_ranges=[DateRange(start_date='2021-01-31',
                                                      end_date='today')])
    response = client.run_report(request)

Question 2 )
I have different events like Clicks, search, ProviderCardClicked and each of these events has a set of metrics
example - Event = Click has metrics = campaign, link_url, link_domain, ga_session_id.
How do I access for this Event all these metrics.

**Comment by busunkim96** [comment]
@ikuleshov Could you take a look?

**Comment by sree80** [comment]
request = RunReportRequest(entity=Entity(property_id=property_id),
dimensions=[Dimension(name='EventName')],
metrics=[Metric(name='EventCount')],
date_ranges=[DateRange(start_date='2021-01-31',
end_date='today')])

response = client.run_report(request)
This is what I have. can you please give an example of how to access custom events

**Comment by brettsneed** [comment]
Hi @sree80 ,
These are answers to your questions:

> Question 1 ) How to access multiple dimensions and Metrics ?

This is an example:

```
    request = RunReportRequest(
      entity=Entity(property_id=property_id),
      date_ranges=[DateRange(start_date='365daysAgo',end_date='yesterday')],
      dimensions=[Dimension(name='firstUserSource'),
                  Dimension(name='firstUserMedium'),
                  Dimension(name='firstUserCampaignName')],
      metrics=[Metric(name='sessions'),
               Metric(name='conversions'),
               Metric(name='totalRevenue')]
      )
    response = client.run_report(request)
```

> Question 2 ) I have different events like Clicks, search, ProviderCardClicked and each of these events has a set of metrics example - Event = Click has metrics = campaign, link_url, link_domain, ga_session_id.
How do I access for this Event all these metrics?

campaign, link_url, link_domain, and ga_session_id are common custom event parameters. To access custom event parameters in the Data API, you need to register the parameters as custom definitions. This [article](https://support.google.com/analytics/answer/10075209) describes registering custom event parameters. This [developer's page](https://developers.google.com/analytics/devguides/reporting/data/v1/advanced#event-scoped_custom_dimensions) shows an example API request. For example, you would use "customEvent:link_url" as the dimension name for the event parameter "link_url".

**Comment by parthea** [comment]
Hi @sree80,

I'm going to close this issue as a response was provided but please re-open this issue if you require additional information.
